### ISSUE TITLE
API: Subgraph vaults, users

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-bot#84]
- A subgraph URL for each network (not an environment variable)
- Add endpoints below:

`/vaults`
Return a JSON response using the example vaults.js query https://github.com/open-dollar/od-subgraph/blob/main/queries/vaults.js 

`/user?address=<address>`
Return the response from the example user.js query

**Comment by jahabeebs** [comment]
@pi0neerpat In the latest SDK the subgraph is https://api.studio.thegraph.com/proxy/52770/open-dollar---testnet/v1.6.5-rc.1/graphql

and when I run the vaults query against this subgraph I get the error Type `Query` has no field `vaults`. Is there a newer subgraph I should be using? and if so we should update the SDK to use it so that we can keep our subgraphs in sync with the geb object (which is how the app and bot repo know which subgraph to access)

**Comment by jahabeebs** [comment]
@pi0neerpat Do you want me to replace the current /user endpoint, add the new query info to it, or should we add a new /userInfo endpoint?

**Comment by pi0neerpat** [comment]
Lets make this a new endpoint `uservaults`
